[ ca ]
default_ca = myca

[ myca ]
dir = ./
new_certs_dir = $dir
unique_subject = no
certificate = $dir/localhost_openssl_Root_CA.crt
database = $dir/certindex
private_key = $dir/localhost_openssl_Root_CA.key
serial = $dir/certserial
default_days = 730
default_md = sha256
policy = myca_policy
x509_extensions = myca_extensions
crlnumber = $dir/crlnumber
default_crl_days = 730

[ myca_policy ]
commonName = supplied
stateOrProvinceName = optional 
countryName = optional
emailAddress = optional
organizationName = optional
organizationalUnitName = optional

[ myca_extensions ]
basicConstraints = critical,CA:TRUE
keyUsage = critical,any
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
keyUsage = digitalSignature,keyEncipherment,cRLSign,keyCertSign

[ v3_ca ]
basicConstraints = critical,CA:TRUE,pathlen:2
keyUsage = critical,any
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
keyUsage = digitalSignature,keyEncipherment,cRLSign,keyCertSign
